### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by bbecausereasonss** [nqthqn/obsidian-wordy#10]
Keeps saying 'oops synonym not found' no matter what word I try.

**Comment by nqthqn** [comment]
I wonder if this was a Datamuse API issue? I'll report errors.

**Comment by nqthqn** [comment]
![image](https://github.com/nqthqn/obsidian-wordy/assets/857356/0c580ba7-3224-48c3-9933-0d3eabfccbd4)

Pushing change now.

Thanks for the good idea @prehensileBBC :)
