### ISSUE TITLE
Is it possible to use the Wordy plugin while offline?

### ISSUE THREAD

**Issue by Maskscot** [nqthqn/obsidian-wordy#12]
This plugin is absolutely vital for me to take in information quickly, so I was perplexed to find out it didn't work offline.
Is there a way around this?

https://github.com/nqthqn/obsidian-wordy/assets/112918049/9456da2d-697d-4992-8061-6fba4a46665a

Here's the file for my vault to test: 
[maskscot-test.zip](https://github.com/nqthqn/obsidian-wordy/files/11991043/maskscot-test.zip)

**Comment by nqthqn** [comment]
Hypothetically, yes. DatamuseAPI uses freely available sources —


https://www.datamuse.com/api/

> Data sources
> The Datamuse API leans on many freely available data sources to do its work:
>Phonetic data: The [CMU pronouncing dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict) is used as a source of phonetic transcriptions for the "sounds-like" constraint and for the various English-language phonetic relations such as perfect rhymes and homophones. The "approximate rhymes" constraint ("rel_nry") is based on this data as well as an analysis of lyrics and poetry on the Web (via the [Common Crawl](https://commoncrawl.org/)).
Corpus-based data: The [Google Books Ngrams](https://storage.googleapis.com/books/ngrams/books/datasetsv2.html) data set is used to build the language model that scores candidate words by context, and also for some of the lexical relations. [word2vec](https://code.google.com/archive/p/word2vec/) is used for reranking result sets by topic (the "topics" parameter). word2vec as well as the excellent [Paraphrase Database](https://www.cis.upenn.edu/~ccb/ppdb/) are used to backfill the results for single-word "means-like" constraints (the "ml" parameter); in particular, the "XXL" lexical paraphrases are used, without modification.
Semantic knowledge: [WordNet 3.0](https://wordnet.princeton.edu/) is used for several of the static semantic lexical relations. For the "means-like" ("ml") constraint, dozens of online dictionaries crawled by [OneLook](https://onelook.com/) are used in addition to WordNet. Definitions come from both WordNet and [Wiktionary](https://www.wiktionary.org/). (Kudos to the excellent [wiktextract](https://github.com/tatuylonen/wiktextract) for making it easy to to process Wiktionary data.)

**Comment by nqthqn** [comment]
I added error reporting for when the plugin cannot access the API in #14
