### ISSUE TITLE
Update Issue, the Wordy Plugin doesn't load.

### ISSUE THREAD

**Issue by Maskscot** [nqthqn/obsidian-wordy#16]
When I try to update/install the Wordy Plugin to its current version, it refuses to enable.

https://github.com/nqthqn/obsidian-wordy/assets/112918049/21d38f77-3e71-4e9e-acb0-d5cbd1f7e4bb

**Comment by pm64** [comment]
Similar issue here -- except in my case, my current version (displayed as "1.0.0") simply won't update to the current version, displayed as "1.2.0":

![image](https://github.com/nqthqn/obsidian-wordy/assets/10715458/0bb3d2f6-7d08-418b-8945-b101ff48c3f9)

This is in Obsidian v1.4.0 (Installer version v1.3.5). I'm not 100% sure if this is related to what @Maskscot is reporting, let me know if I should create a separate issue.

**Comment by Maskscot** [comment]
Oh, it's related alright.

**Comment by IFcoltransG** [comment]
For diagnostics, the specific error I get when trying to install or update the package is:
```js
Error: Request failed, status 404
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
```
The error leads to `app.js:1` which is not particularly helpful in minimised code, but it's from a section of code that looks like this pretty-printed (within a `e.prototype.installPlugin = function(e, t, n) {` ... `}`, at column 1972818 or so).
```js
case 3:
    return s = f.sent(),
    console.error(s),
    new OI(bW.msgFailedToInstallPlugin({
        name: r
    })),
    [2];
```

**Comment by usernotnull** [comment]
+1

**Comment by fncll** [comment]
Same issue here as https://github.com/nqthqn/obsidian-wordy/issues/16#issuecomment-1652278072

**Comment by nqthqn** [comment]
@usernotnull  @Maskscot 
@IFcoltransG — Would you mind trying again? I think it's working now. Had to lock down some dependancies to replicate local and CI/CD behavior.

**Comment by usernotnull** [comment]
@nqthqn Plugin installed correctly and enabled, however, none of the commands are available in the command palette for this plugin.

**Comment by IFcoltransG** [comment]
Installs correctly now.
