### ISSUE TITLE
Latest version not installable.

### ISSUE THREAD

**Issue by joethei** [nqthqn/obsidian-wordy#17]
Hi @nqthqn

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason:
- No release for version 1.2.0 available.

We will remove this plugin from the community plugins directory if this issue is not fixed within 30 days.

See also #16

- The Obsidian Team

**Comment by nqthqn** [comment]
After much finagling, the remote CI/CD env now matches my own build context.
