### ISSUE TITLE
Cannot be added to BRAT

### ISSUE THREAD

**Issue by chrisgrieser** [nqthqn/obsidian-wordy#3]
<img width="446" alt="Pasted image 2022-10-28 13 27 31" src="https://user-images.githubusercontent.com/73286100/198576889-4fef67e9-674c-49fe-813e-063995f4c4cc.png">

[BRAT](https://obsidian.md/plugins?id=obsidian42-brat) support is quite useful for beta testers.

**Comment by oldtowneast** [comment]
I had the same issue and installed it manually.

**Comment by gselend4l** [comment]
I had the same issue and installed manually but when I try to activate it I get an error: "failed to load the plugin"

**Comment by nqthqn** [comment]
Hmm, I also get an error about the `manifest.json` file missing. Everything looks good in the Releases,

![image](https://user-images.githubusercontent.com/857356/207472613-26d4918d-3a1f-44ad-803a-38768d7a8014.png)

**Comment by oldtowneast** [comment]
Working now.  Installed by way of BRAT with no issues.  Gave it a shot and it works as intended on my end.  Good work!

**Comment by chrisgrieser** [comment]
hmm, working now on my end, whatever happened, the bug is gone
