### ISSUE TITLE
Wordy: Rhymes

### ISSUE THREAD

**Issue by zipwits** [nqthqn/obsidian-wordy#6]
Wordy: Rhymes command not found. Same with Wordy: Alliterative Synonyms.

**Comment by chi-wi** [comment]
I believe this might have to do with the fact that the plugin store still advocates version 1.0.0?

**Comment by nqthqn** [comment]
Thanks for this feedback @zipwits

@chi-wi I will see what I can do to fix the release semver issue

**Comment by IFcoltransG** [comment]
@nqthqn See my [recent comment](https://github.com/nqthqn/obsidian-wordy/issues/9#issuecomment-1579903536) for what I think is the fix: updating `manifest.json`.

(Although I think most of the files should get updated by the version bump script from your `package.json`.)
