### ISSUE TITLE
Update available Obsidian community plugin version to 1.1.0

### ISSUE THREAD

**Issue by pm64** [nqthqn/obsidian-wordy#9]
The plugin version available through the Obsidian app is version 1.0.0, even though your latest release, and the version containing most of the features described in the README, is version 1.1.0.

**Comment by pm64** [comment]
Not sure if related -- but I noticed that if I explicitly install version 1.1.0 using BRAT ("frozen version"), then that version IS in fact installed, but the version still displays as 1.0.0 in Obsidian.

**Comment by nightgolfer** [comment]
Not sure if relevant, but package.json has this line:
`"version": "1.0.0",`.

Incidentally, does anyone know how to manually install this extension on Linux? I'm running Obsidian Linux on my chromebook, and can't seem to figure out where to place the extension 🤔

**Comment by IFcoltransG** [comment]
According to the [unofficial plugin docs](https://marcus.se.net/obsidian-plugin-docs/publishing/submit-your-plugin#step-1--create-a-release), the version in `manifest.json` needs to be bumped whenever the package is updated. This repo's [`manifest.json`](https://github.com/nqthqn/obsidian-wordy/blob/master/manifest.json#L4) is still set to 1.0.0 which would explain why the updates haven't propagated.

**Comment by nqthqn** [comment]
I think it's available now — 
![image](https://github.com/nqthqn/obsidian-wordy/assets/857356/95ecaa72-0938-451d-aea1-6931464593d8)
